spring:
  application:
    name: USERS-SERVICE
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI}
      name: USERS-SERVICE
      profile: dev
  profiles:
    active: dev