spring:
  application:
    name: USERS-SERVICE
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://config-server:8168/
      name: USERS-SERVICE
  profiles:
    active: mongodb