spring:
  application:
    name: USER-SERVICE
  data:
    mongodb:
      uri: mongodb://admin:admin%4012345@localhost:27017
      database: user_db
  config:
    import: "configserver:"
  cloud:
    config:
      uri: "http://localhost:8168"
  profiles:
    active: mongodb
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      initialInstanceInfoReplicationIntervalSeconds: 5
      registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

