spring:
  application:
    name: authorization-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
      initialInstanceInfoReplicationIntervalSeconds: 5
      registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

management:
  endpoints:
    web:
      exposure:
        include: health, info

server:
  port: 8888
